"""create query_history table

Revision ID: 03ee143dbef5
Revises: 6777b23ea45e
Create Date: 2026-07-10 04:14:18.273958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ee143dbef5'
down_revision: Union[str, None] = '6777b23ea45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('natural_language', sa.Text(), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('was_executed', sa.Boolean(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('execution_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['db_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_history_connection_id'), 'query_history', ['connection_id'], unique=False)
    op.create_index(op.f('ix_query_history_user_id'), 'query_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_history_user_id'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_connection_id'), table_name='query_history')
    op.drop_table('query_history')
    # ### end Alembic commands ###
